site:
  title: Kodein-Framework Documentation
  url: https://docs.kodein.org
  start_page: kodein-framework::index.adoc
  robots: allow
content:
  sources:
    - url: https://github.com/Kodein-Framework/Kodein-DI.git
      branches: ['7.*', '6.5']
      start_path: doc
    - url: https://github.com/Kodein-Framework/Kodein-DB.git
      branches: ['0.*', '1.*']
      start_path: doc
    - url: https://github.com/Kodein-Framework/Kodein-Log.git
      branches: ['0.*', '1.*', 'master']
      start_path: doc
    - url: https://github.com/Kodein-Framework/documentation.git
      branches: master
      start_path: home
ui:
  bundle:
    url: https://github.com/Kodein-Framework/documentation-ui/raw/master/build/ui-bundle-v1.2.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
urls:
#   latest_version_segment_strategy: 'redirect:from'
#   latest_version_segment: 'latest'
  redirect_facility: 'static'
output:
  dir: docs
