site:
  title: Kodein-Framework Documentation
  url: https://kodein.org/documentation/
  start_page: kodein-framework::index.adoc
  robots: allow
content:
  sources:
    - url: https://github.com/Kodein-Framework/Kodein-DI.git
      branches: [master, 7.1, 7.0, 6.5]
      start_path: doc
    - url: https://github.com/Kodein-Framework/Kodein-DB.git
      branches: antora-master
      start_path: doc
    - url: https://github.com/Kodein-Framework/documentation.git
      branches: master
      start_path: home
ui:
  bundle:
    url: https://github.com/Kodein-Framework/documentation-ui/raw/master/build/ui-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
output:
  dir: docs
