site:
  title: Kodein-Framework Documentation
  url: http://docs.kodein.org
  start_page: kodein-framework::index.adoc
  robots: allow
content:
  sources:
    - url: https://github.com/Kodein-Framework/Kodein-DI.git
      branches: [antora-master, 'antora-v7.1', 'antora-v7', 'antora-v6']
      start_path: doc
    - url: https://github.com/Kodein-Framework/Kodein-DB.git
      branches: [master]
      start_path: doc
#    - url: https://github.com/Kodein-Framework/Kodein-Log.git
#      branches: [antora-master]
#      start_path: doc
    - url: https://github.com/Kodein-Framework/documentation.git
      branches: master
      start_path: home
ui:
  bundle:
    url: https://github.com/Kodein-Framework/documentation-ui/raw/master/build/ui-bundle-v1.1.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
output:
  dir: docs
